custom_cleaning:
  target:
    entity:
      domain: vacuum
  fields:
    mode:
      default: 2
      example: 2
      selector:
        select:
          options:
            - label: Eco
              value: "1"
            - label: Turbo
              value: "2"
    navigation:
      default: 1
      example: 1
      selector:
        select:
          options:
            - label: Normal
              value: "1"
            - label: Extra care
              value: "2"
            - label: Deep
              value: "3"
    category:
      default: 4
      example: 4
      selector:
        select:
          options:
            - label: No map
              value: "2"
            - label: Use map
              value: "4"
    zone:
      example: Kitchen
      selector:
        text:
